// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDNDf9Xq_Batul9KBaIOGrvIFxwxl5H1Vs',
    appId: '1:583511512301:web:864abfadf26d9f98dd28e4',
    messagingSenderId: '583511512301',
    projectId: 'scholardoc-40e03',
    databaseURL: 'https://scholardoc-40e03-default-rtdb.firebaseio.com',
    authDomain: 'scholardoc-40e03.firebaseapp.com',
    storageBucket: 'scholardoc-40e03.firebasestorage.app',
    measurementId: 'G-1RL19XQ1PY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKFEf2kVwuCGQQYaeBtsMaeDZiA0sXv_E',
    appId: '1:583511512301:android:8b768cedf256c9c8dd28e4',
    messagingSenderId: '583511512301',
    projectId: 'scholardoc-40e03',
    databaseURL: 'https://scholardoc-40e03-default-rtdb.firebaseio.com',
    storageBucket: 'scholardoc-40e03.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCg5PV6ODjYcSBN585UFqsNkeByex0Mo9o',
    appId: '1:583511512301:ios:23db6bd502fc4d92dd28e4',
    messagingSenderId: '583511512301',
    projectId: 'scholardoc-40e03',
    databaseURL: 'https://scholardoc-40e03-default-rtdb.firebaseio.com',
    storageBucket: 'scholardoc-40e03.firebasestorage.app',
    iosBundleId: 'com.example.tesdocProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCg5PV6ODjYcSBN585UFqsNkeByex0Mo9o',
    appId: '1:583511512301:ios:23db6bd502fc4d92dd28e4',
    messagingSenderId: '583511512301',
    projectId: 'scholardoc-40e03',
    databaseURL: 'https://scholardoc-40e03-default-rtdb.firebaseio.com',
    storageBucket: 'scholardoc-40e03.firebasestorage.app',
    iosBundleId: 'com.example.tesdocProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDNDf9Xq_Batul9KBaIOGrvIFxwxl5H1Vs',
    appId: '1:583511512301:web:b915ae1c2e9c5ebadd28e4',
    messagingSenderId: '583511512301',
    projectId: 'scholardoc-40e03',
    databaseURL: 'https://scholardoc-40e03-default-rtdb.firebaseio.com',
    authDomain: 'scholardoc-40e03.firebaseapp.com',
    storageBucket: 'scholardoc-40e03.firebasestorage.app',
    measurementId: 'G-6M6DN3KSZK',
  );
}
